// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package jp.co.cyberagent.aeromock.cli.schema


/** JUnit test result schema for the Apache Ant JUnit and JUnitReport tasks
Copyright © 2011, Windy Road Technology Pty. Limited
The Apache Ant JUnit XML Schema is distributed under the terms of the GNU Lesser General Public License (LGPL) http://www.gnu.org/licenses/lgpl.html
Permission to waive conditions of this license may be requested from Windy Road Support (http://windyroad.org/support).
*/


case class Testsuite(properties: jp.co.cyberagent.aeromock.cli.schema.Properties,
  testcase: Seq[jp.co.cyberagent.aeromock.cli.schema.Testcase] = Nil,
  systemu45out: String,
  systemu45err: String,
  name: String,
  timestamp: javax.xml.datatype.XMLGregorianCalendar,
  hostname: String,
  tests: Int,
  failures: Int,
  errors: Int,
  time: BigDecimal,
  packageValue: String,
  id: Int) extends Testsuitable


case class Testsuites(testsuite: jp.co.cyberagent.aeromock.cli.schema.Testsuite*)


case class Property(name: String,
  valueAttribute: String)


case class Properties(property: jp.co.cyberagent.aeromock.cli.schema.Property*)


case class Error(value: String,
  message: Option[String] = None,
  typeValue: String) extends TestcaseOption


case class FailureType(value: String,
  message: Option[String] = None,
  typeValue: String) extends TestcaseOption


case class Testcase(testcaseoption: Option[scalaxb.DataRecord[jp.co.cyberagent.aeromock.cli.schema.TestcaseOption]] = None,
  name: String,
  classname: String,
  time: BigDecimal)

trait TestcaseOption

/** Contains the results of exexuting a testsuite
*/
trait Testsuitable {
  val properties: jp.co.cyberagent.aeromock.cli.schema.Properties
  val testcase: Seq[jp.co.cyberagent.aeromock.cli.schema.Testcase]
  val systemu45out: String
  val systemu45err: String
  val name: String
  val timestamp: javax.xml.datatype.XMLGregorianCalendar
  val hostname: String
  val tests: Int
  val failures: Int
  val errors: Int
  val time: BigDecimal
}


/** Contains the results of exexuting a testsuite
*/
case class TestsuiteType(properties: jp.co.cyberagent.aeromock.cli.schema.Properties,
  testcase: Seq[jp.co.cyberagent.aeromock.cli.schema.Testcase] = Nil,
  systemu45out: String,
  systemu45err: String,
  name: String,
  timestamp: javax.xml.datatype.XMLGregorianCalendar,
  hostname: String,
  tests: Int,
  failures: Int,
  errors: Int,
  time: BigDecimal) extends Testsuitable

