// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/various_nest.proto

package protobuf.schema;

public final class VariousNestOuterClass {
  private VariousNestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VariousNestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.schema.VariousNest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string textTagSize1 = 1;</code>
     */
    boolean hasTextTagSize1();
    /**
     * <code>required string textTagSize1 = 1;</code>
     */
    java.lang.String getTextTagSize1();
    /**
     * <code>required string textTagSize1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextTagSize1Bytes();

    /**
     * <code>required string textTagSize2 = 16;</code>
     */
    boolean hasTextTagSize2();
    /**
     * <code>required string textTagSize2 = 16;</code>
     */
    java.lang.String getTextTagSize2();
    /**
     * <code>required string textTagSize2 = 16;</code>
     */
    com.google.protobuf.ByteString
        getTextTagSize2Bytes();

    /**
     * <code>required string textTagSize3 = 2048;</code>
     */
    boolean hasTextTagSize3();
    /**
     * <code>required string textTagSize3 = 2048;</code>
     */
    java.lang.String getTextTagSize3();
    /**
     * <code>required string textTagSize3 = 2048;</code>
     */
    com.google.protobuf.ByteString
        getTextTagSize3Bytes();
  }
  /**
   * Protobuf type {@code protobuf.schema.VariousNest}
   */
  public static final class VariousNest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.schema.VariousNest)
      VariousNestOrBuilder {
    // Use VariousNest.newBuilder() to construct.
    private VariousNest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VariousNest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VariousNest defaultInstance;
    public static VariousNest getDefaultInstance() {
      return defaultInstance;
    }

    public VariousNest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VariousNest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              textTagSize1_ = bs;
              break;
            }
            case 130: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              textTagSize2_ = bs;
              break;
            }
            case 16386: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              textTagSize3_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.schema.VariousNestOuterClass.internal_static_protobuf_schema_VariousNest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.schema.VariousNestOuterClass.internal_static_protobuf_schema_VariousNest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.schema.VariousNestOuterClass.VariousNest.class, protobuf.schema.VariousNestOuterClass.VariousNest.Builder.class);
    }

    public static com.google.protobuf.Parser<VariousNest> PARSER =
        new com.google.protobuf.AbstractParser<VariousNest>() {
      public VariousNest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VariousNest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VariousNest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEXTTAGSIZE1_FIELD_NUMBER = 1;
    private java.lang.Object textTagSize1_;
    /**
     * <code>required string textTagSize1 = 1;</code>
     */
    public boolean hasTextTagSize1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string textTagSize1 = 1;</code>
     */
    public java.lang.String getTextTagSize1() {
      java.lang.Object ref = textTagSize1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          textTagSize1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string textTagSize1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextTagSize1Bytes() {
      java.lang.Object ref = textTagSize1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textTagSize1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXTTAGSIZE2_FIELD_NUMBER = 16;
    private java.lang.Object textTagSize2_;
    /**
     * <code>required string textTagSize2 = 16;</code>
     */
    public boolean hasTextTagSize2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string textTagSize2 = 16;</code>
     */
    public java.lang.String getTextTagSize2() {
      java.lang.Object ref = textTagSize2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          textTagSize2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string textTagSize2 = 16;</code>
     */
    public com.google.protobuf.ByteString
        getTextTagSize2Bytes() {
      java.lang.Object ref = textTagSize2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textTagSize2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXTTAGSIZE3_FIELD_NUMBER = 2048;
    private java.lang.Object textTagSize3_;
    /**
     * <code>required string textTagSize3 = 2048;</code>
     */
    public boolean hasTextTagSize3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string textTagSize3 = 2048;</code>
     */
    public java.lang.String getTextTagSize3() {
      java.lang.Object ref = textTagSize3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          textTagSize3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string textTagSize3 = 2048;</code>
     */
    public com.google.protobuf.ByteString
        getTextTagSize3Bytes() {
      java.lang.Object ref = textTagSize3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        textTagSize3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      textTagSize1_ = "";
      textTagSize2_ = "";
      textTagSize3_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTextTagSize1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTextTagSize2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTextTagSize3()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextTagSize1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(16, getTextTagSize2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(2048, getTextTagSize3Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextTagSize1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getTextTagSize2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2048, getTextTagSize3Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.schema.VariousNestOuterClass.VariousNest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.schema.VariousNestOuterClass.VariousNest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.schema.VariousNestOuterClass.VariousNest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.schema.VariousNestOuterClass.VariousNest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.schema.VariousNestOuterClass.VariousNest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.schema.VariousNestOuterClass.VariousNest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.schema.VariousNestOuterClass.VariousNest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.schema.VariousNestOuterClass.VariousNest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.schema.VariousNestOuterClass.VariousNest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.schema.VariousNestOuterClass.VariousNest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.schema.VariousNestOuterClass.VariousNest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.schema.VariousNest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.schema.VariousNest)
        protobuf.schema.VariousNestOuterClass.VariousNestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.schema.VariousNestOuterClass.internal_static_protobuf_schema_VariousNest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.schema.VariousNestOuterClass.internal_static_protobuf_schema_VariousNest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.schema.VariousNestOuterClass.VariousNest.class, protobuf.schema.VariousNestOuterClass.VariousNest.Builder.class);
      }

      // Construct using protobuf.schema.VariousNestOuterClass.VariousNest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        textTagSize1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        textTagSize2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        textTagSize3_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.schema.VariousNestOuterClass.internal_static_protobuf_schema_VariousNest_descriptor;
      }

      public protobuf.schema.VariousNestOuterClass.VariousNest getDefaultInstanceForType() {
        return protobuf.schema.VariousNestOuterClass.VariousNest.getDefaultInstance();
      }

      public protobuf.schema.VariousNestOuterClass.VariousNest build() {
        protobuf.schema.VariousNestOuterClass.VariousNest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.schema.VariousNestOuterClass.VariousNest buildPartial() {
        protobuf.schema.VariousNestOuterClass.VariousNest result = new protobuf.schema.VariousNestOuterClass.VariousNest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.textTagSize1_ = textTagSize1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.textTagSize2_ = textTagSize2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.textTagSize3_ = textTagSize3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.schema.VariousNestOuterClass.VariousNest) {
          return mergeFrom((protobuf.schema.VariousNestOuterClass.VariousNest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.schema.VariousNestOuterClass.VariousNest other) {
        if (other == protobuf.schema.VariousNestOuterClass.VariousNest.getDefaultInstance()) return this;
        if (other.hasTextTagSize1()) {
          bitField0_ |= 0x00000001;
          textTagSize1_ = other.textTagSize1_;
          onChanged();
        }
        if (other.hasTextTagSize2()) {
          bitField0_ |= 0x00000002;
          textTagSize2_ = other.textTagSize2_;
          onChanged();
        }
        if (other.hasTextTagSize3()) {
          bitField0_ |= 0x00000004;
          textTagSize3_ = other.textTagSize3_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTextTagSize1()) {
          
          return false;
        }
        if (!hasTextTagSize2()) {
          
          return false;
        }
        if (!hasTextTagSize3()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.schema.VariousNestOuterClass.VariousNest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.schema.VariousNestOuterClass.VariousNest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object textTagSize1_ = "";
      /**
       * <code>required string textTagSize1 = 1;</code>
       */
      public boolean hasTextTagSize1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string textTagSize1 = 1;</code>
       */
      public java.lang.String getTextTagSize1() {
        java.lang.Object ref = textTagSize1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            textTagSize1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string textTagSize1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextTagSize1Bytes() {
        java.lang.Object ref = textTagSize1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          textTagSize1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string textTagSize1 = 1;</code>
       */
      public Builder setTextTagSize1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        textTagSize1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string textTagSize1 = 1;</code>
       */
      public Builder clearTextTagSize1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        textTagSize1_ = getDefaultInstance().getTextTagSize1();
        onChanged();
        return this;
      }
      /**
       * <code>required string textTagSize1 = 1;</code>
       */
      public Builder setTextTagSize1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        textTagSize1_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object textTagSize2_ = "";
      /**
       * <code>required string textTagSize2 = 16;</code>
       */
      public boolean hasTextTagSize2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string textTagSize2 = 16;</code>
       */
      public java.lang.String getTextTagSize2() {
        java.lang.Object ref = textTagSize2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            textTagSize2_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string textTagSize2 = 16;</code>
       */
      public com.google.protobuf.ByteString
          getTextTagSize2Bytes() {
        java.lang.Object ref = textTagSize2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          textTagSize2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string textTagSize2 = 16;</code>
       */
      public Builder setTextTagSize2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        textTagSize2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string textTagSize2 = 16;</code>
       */
      public Builder clearTextTagSize2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        textTagSize2_ = getDefaultInstance().getTextTagSize2();
        onChanged();
        return this;
      }
      /**
       * <code>required string textTagSize2 = 16;</code>
       */
      public Builder setTextTagSize2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        textTagSize2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object textTagSize3_ = "";
      /**
       * <code>required string textTagSize3 = 2048;</code>
       */
      public boolean hasTextTagSize3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string textTagSize3 = 2048;</code>
       */
      public java.lang.String getTextTagSize3() {
        java.lang.Object ref = textTagSize3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            textTagSize3_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string textTagSize3 = 2048;</code>
       */
      public com.google.protobuf.ByteString
          getTextTagSize3Bytes() {
        java.lang.Object ref = textTagSize3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          textTagSize3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string textTagSize3 = 2048;</code>
       */
      public Builder setTextTagSize3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        textTagSize3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string textTagSize3 = 2048;</code>
       */
      public Builder clearTextTagSize3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        textTagSize3_ = getDefaultInstance().getTextTagSize3();
        onChanged();
        return this;
      }
      /**
       * <code>required string textTagSize3 = 2048;</code>
       */
      public Builder setTextTagSize3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        textTagSize3_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.schema.VariousNest)
    }

    static {
      defaultInstance = new VariousNest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.schema.VariousNest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_schema_VariousNest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_schema_VariousNest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031schema/various_nest.proto\022\017protobuf.sc" +
      "hema\"P\n\013VariousNest\022\024\n\014textTagSize1\030\001 \002(" +
      "\t\022\024\n\014textTagSize2\030\020 \002(\t\022\025\n\014textTagSize3\030" +
      "\200\020 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_schema_VariousNest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_schema_VariousNest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_schema_VariousNest_descriptor,
        new java.lang.String[] { "TextTagSize1", "TextTagSize2", "TextTagSize3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
