// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/nest2.proto

package protobuf.api;

public final class Nest2 {
  private Nest2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Nest2RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.api.Nest2Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code protobuf.api.Nest2Request}
   */
  public static final class Nest2Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.api.Nest2Request)
      Nest2RequestOrBuilder {
    // Use Nest2Request.newBuilder() to construct.
    private Nest2Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Nest2Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Nest2Request defaultInstance;
    public static Nest2Request getDefaultInstance() {
      return defaultInstance;
    }

    public Nest2Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Nest2Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              text_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.api.Nest2.Nest2Request.class, protobuf.api.Nest2.Nest2Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Nest2Request> PARSER =
        new com.google.protobuf.AbstractParser<Nest2Request>() {
      public Nest2Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Nest2Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Nest2Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>required string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.api.Nest2.Nest2Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Nest2.Nest2Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Nest2.Nest2Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Nest2.Nest2Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Nest2.Nest2Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Nest2.Nest2Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.api.Nest2.Nest2Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.api.Nest2.Nest2Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.api.Nest2.Nest2Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Nest2.Nest2Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.api.Nest2.Nest2Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.api.Nest2Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.api.Nest2Request)
        protobuf.api.Nest2.Nest2RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.api.Nest2.Nest2Request.class, protobuf.api.Nest2.Nest2Request.Builder.class);
      }

      // Construct using protobuf.api.Nest2.Nest2Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Request_descriptor;
      }

      public protobuf.api.Nest2.Nest2Request getDefaultInstanceForType() {
        return protobuf.api.Nest2.Nest2Request.getDefaultInstance();
      }

      public protobuf.api.Nest2.Nest2Request build() {
        protobuf.api.Nest2.Nest2Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.api.Nest2.Nest2Request buildPartial() {
        protobuf.api.Nest2.Nest2Request result = new protobuf.api.Nest2.Nest2Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.api.Nest2.Nest2Request) {
          return mergeFrom((protobuf.api.Nest2.Nest2Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.api.Nest2.Nest2Request other) {
        if (other == protobuf.api.Nest2.Nest2Request.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.api.Nest2.Nest2Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.api.Nest2.Nest2Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.api.Nest2Request)
    }

    static {
      defaultInstance = new Nest2Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.api.Nest2Request)
  }

  public interface Nest2ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.api.Nest2Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
     */
    boolean hasInner();
    /**
     * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
     */
    protobuf.api.Nest2.Nest2Response.Nest2Inner getInner();
    /**
     * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
     */
    protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder getInnerOrBuilder();

    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    java.util.List<protobuf.api.Nest2.Nest2Response.Nest2Inner> 
        getInnerListList();
    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    protobuf.api.Nest2.Nest2Response.Nest2Inner getInnerList(int index);
    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    int getInnerListCount();
    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    java.util.List<? extends protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder> 
        getInnerListOrBuilderList();
    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder getInnerListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.api.Nest2Response}
   */
  public static final class Nest2Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.api.Nest2Response)
      Nest2ResponseOrBuilder {
    // Use Nest2Response.newBuilder() to construct.
    private Nest2Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Nest2Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Nest2Response defaultInstance;
    public static Nest2Response getDefaultInstance() {
      return defaultInstance;
    }

    public Nest2Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Nest2Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 18: {
              protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = inner_.toBuilder();
              }
              inner_ = input.readMessage(protobuf.api.Nest2.Nest2Response.Nest2Inner.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(inner_);
                inner_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                innerList_ = new java.util.ArrayList<protobuf.api.Nest2.Nest2Response.Nest2Inner>();
                mutable_bitField0_ |= 0x00000004;
              }
              innerList_.add(input.readMessage(protobuf.api.Nest2.Nest2Response.Nest2Inner.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          innerList_ = java.util.Collections.unmodifiableList(innerList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.api.Nest2.Nest2Response.class, protobuf.api.Nest2.Nest2Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Nest2Response> PARSER =
        new com.google.protobuf.AbstractParser<Nest2Response>() {
      public Nest2Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Nest2Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Nest2Response> getParserForType() {
      return PARSER;
    }

    public interface Nest2InnerOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.api.Nest2Response.Nest2Inner)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 id = 10;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 10;</code>
       */
      int getId();

      /**
       * <code>required string name = 20;</code>
       */
      boolean hasName();
      /**
       * <code>required string name = 20;</code>
       */
      java.lang.String getName();
      /**
       * <code>required string name = 20;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code protobuf.api.Nest2Response.Nest2Inner}
     */
    public static final class Nest2Inner extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:protobuf.api.Nest2Response.Nest2Inner)
        Nest2InnerOrBuilder {
      // Use Nest2Inner.newBuilder() to construct.
      private Nest2Inner(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Nest2Inner(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Nest2Inner defaultInstance;
      public static Nest2Inner getDefaultInstance() {
        return defaultInstance;
      }

      public Nest2Inner getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Nest2Inner(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 80: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 162: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                name_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_Nest2Inner_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_Nest2Inner_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.api.Nest2.Nest2Response.Nest2Inner.class, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder.class);
      }

      public static com.google.protobuf.Parser<Nest2Inner> PARSER =
          new com.google.protobuf.AbstractParser<Nest2Inner>() {
        public Nest2Inner parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Nest2Inner(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Nest2Inner> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 10;
      private int id_;
      /**
       * <code>required int32 id = 10;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 10;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int NAME_FIELD_NUMBER = 20;
      private java.lang.Object name_;
      /**
       * <code>required string name = 20;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 20;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string name = 20;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        id_ = 0;
        name_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(10, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(20, getNameBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(10, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(20, getNameBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static protobuf.api.Nest2.Nest2Response.Nest2Inner parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(protobuf.api.Nest2.Nest2Response.Nest2Inner prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobuf.api.Nest2Response.Nest2Inner}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protobuf.api.Nest2Response.Nest2Inner)
          protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_Nest2Inner_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_Nest2Inner_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protobuf.api.Nest2.Nest2Response.Nest2Inner.class, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder.class);
        }

        // Construct using protobuf.api.Nest2.Nest2Response.Nest2Inner.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_Nest2Inner_descriptor;
        }

        public protobuf.api.Nest2.Nest2Response.Nest2Inner getDefaultInstanceForType() {
          return protobuf.api.Nest2.Nest2Response.Nest2Inner.getDefaultInstance();
        }

        public protobuf.api.Nest2.Nest2Response.Nest2Inner build() {
          protobuf.api.Nest2.Nest2Response.Nest2Inner result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public protobuf.api.Nest2.Nest2Response.Nest2Inner buildPartial() {
          protobuf.api.Nest2.Nest2Response.Nest2Inner result = new protobuf.api.Nest2.Nest2Response.Nest2Inner(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.name_ = name_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protobuf.api.Nest2.Nest2Response.Nest2Inner) {
            return mergeFrom((protobuf.api.Nest2.Nest2Response.Nest2Inner)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protobuf.api.Nest2.Nest2Response.Nest2Inner other) {
          if (other == protobuf.api.Nest2.Nest2Response.Nest2Inner.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasName()) {
            bitField0_ |= 0x00000002;
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasName()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protobuf.api.Nest2.Nest2Response.Nest2Inner parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protobuf.api.Nest2.Nest2Response.Nest2Inner) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int id_ ;
        /**
         * <code>required int32 id = 10;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 id = 10;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 10;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 10;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>required string name = 20;</code>
         */
        public boolean hasName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string name = 20;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              name_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string name = 20;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string name = 20;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 20;</code>
         */
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>required string name = 20;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          name_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protobuf.api.Nest2Response.Nest2Inner)
      }

      static {
        defaultInstance = new Nest2Inner(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:protobuf.api.Nest2Response.Nest2Inner)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int INNER_FIELD_NUMBER = 2;
    private protobuf.api.Nest2.Nest2Response.Nest2Inner inner_;
    /**
     * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
     */
    public boolean hasInner() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
     */
    public protobuf.api.Nest2.Nest2Response.Nest2Inner getInner() {
      return inner_;
    }
    /**
     * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
     */
    public protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder getInnerOrBuilder() {
      return inner_;
    }

    public static final int INNERLIST_FIELD_NUMBER = 3;
    private java.util.List<protobuf.api.Nest2.Nest2Response.Nest2Inner> innerList_;
    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    public java.util.List<protobuf.api.Nest2.Nest2Response.Nest2Inner> getInnerListList() {
      return innerList_;
    }
    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    public java.util.List<? extends protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder> 
        getInnerListOrBuilderList() {
      return innerList_;
    }
    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    public int getInnerListCount() {
      return innerList_.size();
    }
    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    public protobuf.api.Nest2.Nest2Response.Nest2Inner getInnerList(int index) {
      return innerList_.get(index);
    }
    /**
     * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
     */
    public protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder getInnerListOrBuilder(
        int index) {
      return innerList_.get(index);
    }

    private void initFields() {
      id_ = 0;
      inner_ = protobuf.api.Nest2.Nest2Response.Nest2Inner.getDefaultInstance();
      innerList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInner()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getInner().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getInnerListCount(); i++) {
        if (!getInnerList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, inner_);
      }
      for (int i = 0; i < innerList_.size(); i++) {
        output.writeMessage(3, innerList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, inner_);
      }
      for (int i = 0; i < innerList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, innerList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.api.Nest2.Nest2Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Nest2.Nest2Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Nest2.Nest2Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Nest2.Nest2Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Nest2.Nest2Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Nest2.Nest2Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.api.Nest2.Nest2Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.api.Nest2.Nest2Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.api.Nest2.Nest2Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Nest2.Nest2Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.api.Nest2.Nest2Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.api.Nest2Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.api.Nest2Response)
        protobuf.api.Nest2.Nest2ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.api.Nest2.Nest2Response.class, protobuf.api.Nest2.Nest2Response.Builder.class);
      }

      // Construct using protobuf.api.Nest2.Nest2Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInnerFieldBuilder();
          getInnerListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (innerBuilder_ == null) {
          inner_ = protobuf.api.Nest2.Nest2Response.Nest2Inner.getDefaultInstance();
        } else {
          innerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (innerListBuilder_ == null) {
          innerList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          innerListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.api.Nest2.internal_static_protobuf_api_Nest2Response_descriptor;
      }

      public protobuf.api.Nest2.Nest2Response getDefaultInstanceForType() {
        return protobuf.api.Nest2.Nest2Response.getDefaultInstance();
      }

      public protobuf.api.Nest2.Nest2Response build() {
        protobuf.api.Nest2.Nest2Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.api.Nest2.Nest2Response buildPartial() {
        protobuf.api.Nest2.Nest2Response result = new protobuf.api.Nest2.Nest2Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (innerBuilder_ == null) {
          result.inner_ = inner_;
        } else {
          result.inner_ = innerBuilder_.build();
        }
        if (innerListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            innerList_ = java.util.Collections.unmodifiableList(innerList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.innerList_ = innerList_;
        } else {
          result.innerList_ = innerListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.api.Nest2.Nest2Response) {
          return mergeFrom((protobuf.api.Nest2.Nest2Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.api.Nest2.Nest2Response other) {
        if (other == protobuf.api.Nest2.Nest2Response.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasInner()) {
          mergeInner(other.getInner());
        }
        if (innerListBuilder_ == null) {
          if (!other.innerList_.isEmpty()) {
            if (innerList_.isEmpty()) {
              innerList_ = other.innerList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureInnerListIsMutable();
              innerList_.addAll(other.innerList_);
            }
            onChanged();
          }
        } else {
          if (!other.innerList_.isEmpty()) {
            if (innerListBuilder_.isEmpty()) {
              innerListBuilder_.dispose();
              innerListBuilder_ = null;
              innerList_ = other.innerList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              innerListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInnerListFieldBuilder() : null;
            } else {
              innerListBuilder_.addAllMessages(other.innerList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasInner()) {
          
          return false;
        }
        if (!getInner().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getInnerListCount(); i++) {
          if (!getInnerList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.api.Nest2.Nest2Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.api.Nest2.Nest2Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private protobuf.api.Nest2.Nest2Response.Nest2Inner inner_ = protobuf.api.Nest2.Nest2Response.Nest2Inner.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.api.Nest2.Nest2Response.Nest2Inner, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder, protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder> innerBuilder_;
      /**
       * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
       */
      public boolean hasInner() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
       */
      public protobuf.api.Nest2.Nest2Response.Nest2Inner getInner() {
        if (innerBuilder_ == null) {
          return inner_;
        } else {
          return innerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
       */
      public Builder setInner(protobuf.api.Nest2.Nest2Response.Nest2Inner value) {
        if (innerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          inner_ = value;
          onChanged();
        } else {
          innerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
       */
      public Builder setInner(
          protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder builderForValue) {
        if (innerBuilder_ == null) {
          inner_ = builderForValue.build();
          onChanged();
        } else {
          innerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
       */
      public Builder mergeInner(protobuf.api.Nest2.Nest2Response.Nest2Inner value) {
        if (innerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              inner_ != protobuf.api.Nest2.Nest2Response.Nest2Inner.getDefaultInstance()) {
            inner_ =
              protobuf.api.Nest2.Nest2Response.Nest2Inner.newBuilder(inner_).mergeFrom(value).buildPartial();
          } else {
            inner_ = value;
          }
          onChanged();
        } else {
          innerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
       */
      public Builder clearInner() {
        if (innerBuilder_ == null) {
          inner_ = protobuf.api.Nest2.Nest2Response.Nest2Inner.getDefaultInstance();
          onChanged();
        } else {
          innerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
       */
      public protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder getInnerBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getInnerFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
       */
      public protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder getInnerOrBuilder() {
        if (innerBuilder_ != null) {
          return innerBuilder_.getMessageOrBuilder();
        } else {
          return inner_;
        }
      }
      /**
       * <code>required .protobuf.api.Nest2Response.Nest2Inner inner = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.api.Nest2.Nest2Response.Nest2Inner, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder, protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder> 
          getInnerFieldBuilder() {
        if (innerBuilder_ == null) {
          innerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protobuf.api.Nest2.Nest2Response.Nest2Inner, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder, protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder>(
                  getInner(),
                  getParentForChildren(),
                  isClean());
          inner_ = null;
        }
        return innerBuilder_;
      }

      private java.util.List<protobuf.api.Nest2.Nest2Response.Nest2Inner> innerList_ =
        java.util.Collections.emptyList();
      private void ensureInnerListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          innerList_ = new java.util.ArrayList<protobuf.api.Nest2.Nest2Response.Nest2Inner>(innerList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.api.Nest2.Nest2Response.Nest2Inner, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder, protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder> innerListBuilder_;

      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public java.util.List<protobuf.api.Nest2.Nest2Response.Nest2Inner> getInnerListList() {
        if (innerListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(innerList_);
        } else {
          return innerListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public int getInnerListCount() {
        if (innerListBuilder_ == null) {
          return innerList_.size();
        } else {
          return innerListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public protobuf.api.Nest2.Nest2Response.Nest2Inner getInnerList(int index) {
        if (innerListBuilder_ == null) {
          return innerList_.get(index);
        } else {
          return innerListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public Builder setInnerList(
          int index, protobuf.api.Nest2.Nest2Response.Nest2Inner value) {
        if (innerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerListIsMutable();
          innerList_.set(index, value);
          onChanged();
        } else {
          innerListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public Builder setInnerList(
          int index, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder builderForValue) {
        if (innerListBuilder_ == null) {
          ensureInnerListIsMutable();
          innerList_.set(index, builderForValue.build());
          onChanged();
        } else {
          innerListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public Builder addInnerList(protobuf.api.Nest2.Nest2Response.Nest2Inner value) {
        if (innerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerListIsMutable();
          innerList_.add(value);
          onChanged();
        } else {
          innerListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public Builder addInnerList(
          int index, protobuf.api.Nest2.Nest2Response.Nest2Inner value) {
        if (innerListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInnerListIsMutable();
          innerList_.add(index, value);
          onChanged();
        } else {
          innerListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public Builder addInnerList(
          protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder builderForValue) {
        if (innerListBuilder_ == null) {
          ensureInnerListIsMutable();
          innerList_.add(builderForValue.build());
          onChanged();
        } else {
          innerListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public Builder addInnerList(
          int index, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder builderForValue) {
        if (innerListBuilder_ == null) {
          ensureInnerListIsMutable();
          innerList_.add(index, builderForValue.build());
          onChanged();
        } else {
          innerListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public Builder addAllInnerList(
          java.lang.Iterable<? extends protobuf.api.Nest2.Nest2Response.Nest2Inner> values) {
        if (innerListBuilder_ == null) {
          ensureInnerListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, innerList_);
          onChanged();
        } else {
          innerListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public Builder clearInnerList() {
        if (innerListBuilder_ == null) {
          innerList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          innerListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public Builder removeInnerList(int index) {
        if (innerListBuilder_ == null) {
          ensureInnerListIsMutable();
          innerList_.remove(index);
          onChanged();
        } else {
          innerListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder getInnerListBuilder(
          int index) {
        return getInnerListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder getInnerListOrBuilder(
          int index) {
        if (innerListBuilder_ == null) {
          return innerList_.get(index);  } else {
          return innerListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public java.util.List<? extends protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder> 
           getInnerListOrBuilderList() {
        if (innerListBuilder_ != null) {
          return innerListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(innerList_);
        }
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder addInnerListBuilder() {
        return getInnerListFieldBuilder().addBuilder(
            protobuf.api.Nest2.Nest2Response.Nest2Inner.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder addInnerListBuilder(
          int index) {
        return getInnerListFieldBuilder().addBuilder(
            index, protobuf.api.Nest2.Nest2Response.Nest2Inner.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.api.Nest2Response.Nest2Inner innerList = 3;</code>
       */
      public java.util.List<protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder> 
           getInnerListBuilderList() {
        return getInnerListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.api.Nest2.Nest2Response.Nest2Inner, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder, protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder> 
          getInnerListFieldBuilder() {
        if (innerListBuilder_ == null) {
          innerListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.api.Nest2.Nest2Response.Nest2Inner, protobuf.api.Nest2.Nest2Response.Nest2Inner.Builder, protobuf.api.Nest2.Nest2Response.Nest2InnerOrBuilder>(
                  innerList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          innerList_ = null;
        }
        return innerListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.api.Nest2Response)
    }

    static {
      defaultInstance = new Nest2Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.api.Nest2Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_Nest2Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_api_Nest2Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_Nest2Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_api_Nest2Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_Nest2Response_Nest2Inner_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_api_Nest2Response_Nest2Inner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017api/nest2.proto\022\014protobuf.api\"\034\n\014Nest2" +
      "Request\022\014\n\004text\030\001 \002(\t\"\265\001\n\rNest2Response\022" +
      "\n\n\002id\030\001 \002(\r\0225\n\005inner\030\002 \002(\0132&.protobuf.ap" +
      "i.Nest2Response.Nest2Inner\0229\n\tinnerList\030" +
      "\003 \003(\0132&.protobuf.api.Nest2Response.Nest2" +
      "Inner\032&\n\nNest2Inner\022\n\n\002id\030\n \002(\005\022\014\n\004name\030" +
      "\024 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_api_Nest2Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_api_Nest2Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_api_Nest2Request_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_protobuf_api_Nest2Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_api_Nest2Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_api_Nest2Response_descriptor,
        new java.lang.String[] { "Id", "Inner", "InnerList", });
    internal_static_protobuf_api_Nest2Response_Nest2Inner_descriptor =
      internal_static_protobuf_api_Nest2Response_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_api_Nest2Response_Nest2Inner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_api_Nest2Response_Nest2Inner_descriptor,
        new java.lang.String[] { "Id", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
