// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/nest1.proto

package protobuf.api;

public final class Nest1 {
  private Nest1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Nest1RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.api.Nest1Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code protobuf.api.Nest1Request}
   */
  public static final class Nest1Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.api.Nest1Request)
      Nest1RequestOrBuilder {
    // Use Nest1Request.newBuilder() to construct.
    private Nest1Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Nest1Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Nest1Request defaultInstance;
    public static Nest1Request getDefaultInstance() {
      return defaultInstance;
    }

    public Nest1Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Nest1Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              text_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.api.Nest1.Nest1Request.class, protobuf.api.Nest1.Nest1Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Nest1Request> PARSER =
        new com.google.protobuf.AbstractParser<Nest1Request>() {
      public Nest1Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Nest1Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Nest1Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>required string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.api.Nest1.Nest1Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Nest1.Nest1Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Nest1.Nest1Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Nest1.Nest1Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Nest1.Nest1Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Nest1.Nest1Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.api.Nest1.Nest1Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.api.Nest1.Nest1Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.api.Nest1.Nest1Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Nest1.Nest1Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.api.Nest1.Nest1Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.api.Nest1Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.api.Nest1Request)
        protobuf.api.Nest1.Nest1RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.api.Nest1.Nest1Request.class, protobuf.api.Nest1.Nest1Request.Builder.class);
      }

      // Construct using protobuf.api.Nest1.Nest1Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Request_descriptor;
      }

      public protobuf.api.Nest1.Nest1Request getDefaultInstanceForType() {
        return protobuf.api.Nest1.Nest1Request.getDefaultInstance();
      }

      public protobuf.api.Nest1.Nest1Request build() {
        protobuf.api.Nest1.Nest1Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.api.Nest1.Nest1Request buildPartial() {
        protobuf.api.Nest1.Nest1Request result = new protobuf.api.Nest1.Nest1Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.api.Nest1.Nest1Request) {
          return mergeFrom((protobuf.api.Nest1.Nest1Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.api.Nest1.Nest1Request other) {
        if (other == protobuf.api.Nest1.Nest1Request.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.api.Nest1.Nest1Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.api.Nest1.Nest1Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.api.Nest1Request)
    }

    static {
      defaultInstance = new Nest1Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.api.Nest1Request)
  }

  public interface Nest1ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.api.Nest1Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required .protobuf.schema.User mainUser = 2;</code>
     */
    boolean hasMainUser();
    /**
     * <code>required .protobuf.schema.User mainUser = 2;</code>
     */
    protobuf.schema.UserOuterClass.User getMainUser();
    /**
     * <code>required .protobuf.schema.User mainUser = 2;</code>
     */
    protobuf.schema.UserOuterClass.UserOrBuilder getMainUserOrBuilder();

    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    java.util.List<protobuf.schema.UserOuterClass.User> 
        getOtherUsersList();
    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    protobuf.schema.UserOuterClass.User getOtherUsers(int index);
    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    int getOtherUsersCount();
    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    java.util.List<? extends protobuf.schema.UserOuterClass.UserOrBuilder> 
        getOtherUsersOrBuilderList();
    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    protobuf.schema.UserOuterClass.UserOrBuilder getOtherUsersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.api.Nest1Response}
   */
  public static final class Nest1Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.api.Nest1Response)
      Nest1ResponseOrBuilder {
    // Use Nest1Response.newBuilder() to construct.
    private Nest1Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Nest1Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Nest1Response defaultInstance;
    public static Nest1Response getDefaultInstance() {
      return defaultInstance;
    }

    public Nest1Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Nest1Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 18: {
              protobuf.schema.UserOuterClass.User.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = mainUser_.toBuilder();
              }
              mainUser_ = input.readMessage(protobuf.schema.UserOuterClass.User.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mainUser_);
                mainUser_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                otherUsers_ = new java.util.ArrayList<protobuf.schema.UserOuterClass.User>();
                mutable_bitField0_ |= 0x00000004;
              }
              otherUsers_.add(input.readMessage(protobuf.schema.UserOuterClass.User.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          otherUsers_ = java.util.Collections.unmodifiableList(otherUsers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.api.Nest1.Nest1Response.class, protobuf.api.Nest1.Nest1Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Nest1Response> PARSER =
        new com.google.protobuf.AbstractParser<Nest1Response>() {
      public Nest1Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Nest1Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Nest1Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int MAINUSER_FIELD_NUMBER = 2;
    private protobuf.schema.UserOuterClass.User mainUser_;
    /**
     * <code>required .protobuf.schema.User mainUser = 2;</code>
     */
    public boolean hasMainUser() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protobuf.schema.User mainUser = 2;</code>
     */
    public protobuf.schema.UserOuterClass.User getMainUser() {
      return mainUser_;
    }
    /**
     * <code>required .protobuf.schema.User mainUser = 2;</code>
     */
    public protobuf.schema.UserOuterClass.UserOrBuilder getMainUserOrBuilder() {
      return mainUser_;
    }

    public static final int OTHERUSERS_FIELD_NUMBER = 3;
    private java.util.List<protobuf.schema.UserOuterClass.User> otherUsers_;
    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    public java.util.List<protobuf.schema.UserOuterClass.User> getOtherUsersList() {
      return otherUsers_;
    }
    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    public java.util.List<? extends protobuf.schema.UserOuterClass.UserOrBuilder> 
        getOtherUsersOrBuilderList() {
      return otherUsers_;
    }
    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    public int getOtherUsersCount() {
      return otherUsers_.size();
    }
    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    public protobuf.schema.UserOuterClass.User getOtherUsers(int index) {
      return otherUsers_.get(index);
    }
    /**
     * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
     */
    public protobuf.schema.UserOuterClass.UserOrBuilder getOtherUsersOrBuilder(
        int index) {
      return otherUsers_.get(index);
    }

    private void initFields() {
      id_ = 0;
      mainUser_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
      otherUsers_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMainUser()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMainUser().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getOtherUsersCount(); i++) {
        if (!getOtherUsers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, mainUser_);
      }
      for (int i = 0; i < otherUsers_.size(); i++) {
        output.writeMessage(3, otherUsers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, mainUser_);
      }
      for (int i = 0; i < otherUsers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, otherUsers_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.api.Nest1.Nest1Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Nest1.Nest1Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Nest1.Nest1Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.api.Nest1.Nest1Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.api.Nest1.Nest1Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Nest1.Nest1Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.api.Nest1.Nest1Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.api.Nest1.Nest1Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.api.Nest1.Nest1Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.api.Nest1.Nest1Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.api.Nest1.Nest1Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.api.Nest1Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.api.Nest1Response)
        protobuf.api.Nest1.Nest1ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.api.Nest1.Nest1Response.class, protobuf.api.Nest1.Nest1Response.Builder.class);
      }

      // Construct using protobuf.api.Nest1.Nest1Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMainUserFieldBuilder();
          getOtherUsersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (mainUserBuilder_ == null) {
          mainUser_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
        } else {
          mainUserBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (otherUsersBuilder_ == null) {
          otherUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          otherUsersBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.api.Nest1.internal_static_protobuf_api_Nest1Response_descriptor;
      }

      public protobuf.api.Nest1.Nest1Response getDefaultInstanceForType() {
        return protobuf.api.Nest1.Nest1Response.getDefaultInstance();
      }

      public protobuf.api.Nest1.Nest1Response build() {
        protobuf.api.Nest1.Nest1Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.api.Nest1.Nest1Response buildPartial() {
        protobuf.api.Nest1.Nest1Response result = new protobuf.api.Nest1.Nest1Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (mainUserBuilder_ == null) {
          result.mainUser_ = mainUser_;
        } else {
          result.mainUser_ = mainUserBuilder_.build();
        }
        if (otherUsersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            otherUsers_ = java.util.Collections.unmodifiableList(otherUsers_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.otherUsers_ = otherUsers_;
        } else {
          result.otherUsers_ = otherUsersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.api.Nest1.Nest1Response) {
          return mergeFrom((protobuf.api.Nest1.Nest1Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.api.Nest1.Nest1Response other) {
        if (other == protobuf.api.Nest1.Nest1Response.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasMainUser()) {
          mergeMainUser(other.getMainUser());
        }
        if (otherUsersBuilder_ == null) {
          if (!other.otherUsers_.isEmpty()) {
            if (otherUsers_.isEmpty()) {
              otherUsers_ = other.otherUsers_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureOtherUsersIsMutable();
              otherUsers_.addAll(other.otherUsers_);
            }
            onChanged();
          }
        } else {
          if (!other.otherUsers_.isEmpty()) {
            if (otherUsersBuilder_.isEmpty()) {
              otherUsersBuilder_.dispose();
              otherUsersBuilder_ = null;
              otherUsers_ = other.otherUsers_;
              bitField0_ = (bitField0_ & ~0x00000004);
              otherUsersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOtherUsersFieldBuilder() : null;
            } else {
              otherUsersBuilder_.addAllMessages(other.otherUsers_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasMainUser()) {
          
          return false;
        }
        if (!getMainUser().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getOtherUsersCount(); i++) {
          if (!getOtherUsers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.api.Nest1.Nest1Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.api.Nest1.Nest1Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private protobuf.schema.UserOuterClass.User mainUser_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder> mainUserBuilder_;
      /**
       * <code>required .protobuf.schema.User mainUser = 2;</code>
       */
      public boolean hasMainUser() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protobuf.schema.User mainUser = 2;</code>
       */
      public protobuf.schema.UserOuterClass.User getMainUser() {
        if (mainUserBuilder_ == null) {
          return mainUser_;
        } else {
          return mainUserBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protobuf.schema.User mainUser = 2;</code>
       */
      public Builder setMainUser(protobuf.schema.UserOuterClass.User value) {
        if (mainUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mainUser_ = value;
          onChanged();
        } else {
          mainUserBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.schema.User mainUser = 2;</code>
       */
      public Builder setMainUser(
          protobuf.schema.UserOuterClass.User.Builder builderForValue) {
        if (mainUserBuilder_ == null) {
          mainUser_ = builderForValue.build();
          onChanged();
        } else {
          mainUserBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.schema.User mainUser = 2;</code>
       */
      public Builder mergeMainUser(protobuf.schema.UserOuterClass.User value) {
        if (mainUserBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              mainUser_ != protobuf.schema.UserOuterClass.User.getDefaultInstance()) {
            mainUser_ =
              protobuf.schema.UserOuterClass.User.newBuilder(mainUser_).mergeFrom(value).buildPartial();
          } else {
            mainUser_ = value;
          }
          onChanged();
        } else {
          mainUserBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protobuf.schema.User mainUser = 2;</code>
       */
      public Builder clearMainUser() {
        if (mainUserBuilder_ == null) {
          mainUser_ = protobuf.schema.UserOuterClass.User.getDefaultInstance();
          onChanged();
        } else {
          mainUserBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protobuf.schema.User mainUser = 2;</code>
       */
      public protobuf.schema.UserOuterClass.User.Builder getMainUserBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMainUserFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protobuf.schema.User mainUser = 2;</code>
       */
      public protobuf.schema.UserOuterClass.UserOrBuilder getMainUserOrBuilder() {
        if (mainUserBuilder_ != null) {
          return mainUserBuilder_.getMessageOrBuilder();
        } else {
          return mainUser_;
        }
      }
      /**
       * <code>required .protobuf.schema.User mainUser = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder> 
          getMainUserFieldBuilder() {
        if (mainUserBuilder_ == null) {
          mainUserBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder>(
                  getMainUser(),
                  getParentForChildren(),
                  isClean());
          mainUser_ = null;
        }
        return mainUserBuilder_;
      }

      private java.util.List<protobuf.schema.UserOuterClass.User> otherUsers_ =
        java.util.Collections.emptyList();
      private void ensureOtherUsersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          otherUsers_ = new java.util.ArrayList<protobuf.schema.UserOuterClass.User>(otherUsers_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder> otherUsersBuilder_;

      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public java.util.List<protobuf.schema.UserOuterClass.User> getOtherUsersList() {
        if (otherUsersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(otherUsers_);
        } else {
          return otherUsersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public int getOtherUsersCount() {
        if (otherUsersBuilder_ == null) {
          return otherUsers_.size();
        } else {
          return otherUsersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public protobuf.schema.UserOuterClass.User getOtherUsers(int index) {
        if (otherUsersBuilder_ == null) {
          return otherUsers_.get(index);
        } else {
          return otherUsersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public Builder setOtherUsers(
          int index, protobuf.schema.UserOuterClass.User value) {
        if (otherUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherUsersIsMutable();
          otherUsers_.set(index, value);
          onChanged();
        } else {
          otherUsersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public Builder setOtherUsers(
          int index, protobuf.schema.UserOuterClass.User.Builder builderForValue) {
        if (otherUsersBuilder_ == null) {
          ensureOtherUsersIsMutable();
          otherUsers_.set(index, builderForValue.build());
          onChanged();
        } else {
          otherUsersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public Builder addOtherUsers(protobuf.schema.UserOuterClass.User value) {
        if (otherUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherUsersIsMutable();
          otherUsers_.add(value);
          onChanged();
        } else {
          otherUsersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public Builder addOtherUsers(
          int index, protobuf.schema.UserOuterClass.User value) {
        if (otherUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherUsersIsMutable();
          otherUsers_.add(index, value);
          onChanged();
        } else {
          otherUsersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public Builder addOtherUsers(
          protobuf.schema.UserOuterClass.User.Builder builderForValue) {
        if (otherUsersBuilder_ == null) {
          ensureOtherUsersIsMutable();
          otherUsers_.add(builderForValue.build());
          onChanged();
        } else {
          otherUsersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public Builder addOtherUsers(
          int index, protobuf.schema.UserOuterClass.User.Builder builderForValue) {
        if (otherUsersBuilder_ == null) {
          ensureOtherUsersIsMutable();
          otherUsers_.add(index, builderForValue.build());
          onChanged();
        } else {
          otherUsersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public Builder addAllOtherUsers(
          java.lang.Iterable<? extends protobuf.schema.UserOuterClass.User> values) {
        if (otherUsersBuilder_ == null) {
          ensureOtherUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, otherUsers_);
          onChanged();
        } else {
          otherUsersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public Builder clearOtherUsers() {
        if (otherUsersBuilder_ == null) {
          otherUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          otherUsersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public Builder removeOtherUsers(int index) {
        if (otherUsersBuilder_ == null) {
          ensureOtherUsersIsMutable();
          otherUsers_.remove(index);
          onChanged();
        } else {
          otherUsersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public protobuf.schema.UserOuterClass.User.Builder getOtherUsersBuilder(
          int index) {
        return getOtherUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public protobuf.schema.UserOuterClass.UserOrBuilder getOtherUsersOrBuilder(
          int index) {
        if (otherUsersBuilder_ == null) {
          return otherUsers_.get(index);  } else {
          return otherUsersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public java.util.List<? extends protobuf.schema.UserOuterClass.UserOrBuilder> 
           getOtherUsersOrBuilderList() {
        if (otherUsersBuilder_ != null) {
          return otherUsersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(otherUsers_);
        }
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public protobuf.schema.UserOuterClass.User.Builder addOtherUsersBuilder() {
        return getOtherUsersFieldBuilder().addBuilder(
            protobuf.schema.UserOuterClass.User.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public protobuf.schema.UserOuterClass.User.Builder addOtherUsersBuilder(
          int index) {
        return getOtherUsersFieldBuilder().addBuilder(
            index, protobuf.schema.UserOuterClass.User.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.schema.User otherUsers = 3;</code>
       */
      public java.util.List<protobuf.schema.UserOuterClass.User.Builder> 
           getOtherUsersBuilderList() {
        return getOtherUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder> 
          getOtherUsersFieldBuilder() {
        if (otherUsersBuilder_ == null) {
          otherUsersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.schema.UserOuterClass.User, protobuf.schema.UserOuterClass.User.Builder, protobuf.schema.UserOuterClass.UserOrBuilder>(
                  otherUsers_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          otherUsers_ = null;
        }
        return otherUsersBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.api.Nest1Response)
    }

    static {
      defaultInstance = new Nest1Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.api.Nest1Response)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_Nest1Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_api_Nest1Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_api_Nest1Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_api_Nest1Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017api/nest1.proto\022\014protobuf.api\032\021schema/" +
      "user.proto\"\034\n\014Nest1Request\022\014\n\004text\030\001 \002(\t" +
      "\"o\n\rNest1Response\022\n\n\002id\030\001 \002(\r\022\'\n\010mainUse" +
      "r\030\002 \002(\0132\025.protobuf.schema.User\022)\n\notherU" +
      "sers\030\003 \003(\0132\025.protobuf.schema.User"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.schema.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_protobuf_api_Nest1Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_api_Nest1Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_api_Nest1Request_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_protobuf_api_Nest1Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_api_Nest1Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_api_Nest1Response_descriptor,
        new java.lang.String[] { "Id", "MainUser", "OtherUsers", });
    protobuf.schema.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
